# Generated by Django 5.2.7 on 2025-10-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='brith_date',
            new_name='birth_date',
        ),
    ]
